"""initial migration

Revision ID: 7cf30dbb5558
Revises: 
Create Date: 2020-07-27 14:07:36.516601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf30dbb5558'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('zipcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
